// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var Driver, customGecko, geckodriver, selenium;

  selenium = require('selenium-webdriver');

  geckodriver = require('geckodriver').path;

  customGecko = selenium.Capabilities.phantomjs();

  customGecko.set("firefox.binary.path", geckodriver);

  Driver = function() {
    this.use = new selenium.Builder().withCapabilities(customGecko).build();
    this.use.getWindowHandle();
    return true;
  };

  Driver.prototype.close = function() {
    return this.use.quit();
  };

  module.exports = Driver;

}).call(this);
